### ISSUE TITLE
"Fake" channel stops grabing channels left for file.

### ISSUE THREAD

**Issue by dueler-x** [evoactivity/PlutoIPTV#2]
The script only saves the first eleven channels before NewsmaxTV, this is how the scripts shows it as fake channel:

[INFO] Grabbing EPG...
http://api.pluto.tv/v2/channels?start=2020-09-22%2018%3A00%3A00.000%2B0000&stop=2020-09-23%2002%3A00%3A00.000%2B0000
[DEBUG] Using api.pluto.tv, writing cache.json.
[INFO] Adding Slow TV channel.
[INFO] Adding TYT Network channel.
[INFO] Adding GLORY Kickboxing channel.
[INFO] Adding MST3K channel.
[INFO] Adding NASA TV channel.
[INFO] Adding Bloomberg TV channel.
[INFO] Adding Awesomeness TV channel.
[INFO] Adding Shout! Factory TV channel.
[DEBUG] Skipping 'fake' channel NewsmaxTV.

**Comment by ReenigneArcher** [comment]
@dueler-x if you're okay with running python check out my scripts here (https://github.com/ReenigneArcher/web2tv). Python 2.7 required.

**Comment by ReenigneArcher** [comment]
@evoactivity I haven't looked at the code for your script, but my python script returns a key error on the NewsmaxTV channel mentioned in this issue. It's because the json is missing the `thumbnail` key. I had to add error handling to ignore the key errors and make the value blank if there was a key error.

![image](https://user-images.githubusercontent.com/42013603/102731298-6e569e80-4305-11eb-8ef7-52131500d112.png)

Where as it should contain the thumbnail\path.
![image](https://user-images.githubusercontent.com/42013603/102731353-99d98900-4305-11eb-87fd-08771b9004ca.png)

All of these channels are missing something in at least 1 airing.
`The following json key_errors were found. :[u"program title: Newsmax Live channelName: NewsmaxTV KeyError: 'thumbnail'", u"program title: The Litter channelName: Cats 24/7 KeyError: 'featuredImage'", u"program title: Are You Kitten Me? channelName: Cats 24/7 KeyError: 'featuredImage'", u"program title: Meowathon! channelName: The Pet Collective KeyError: 'featuredImage'", u"program title: Meowathon! channelName: The Pet Collective KeyError: 'featuredImage'", u"program title: Newsmax Live channelName: NewsmaxTV 2 KeyError: 'thumbnail'"]`

Hope it helps!

**Comment by evoactivity** [comment]
Thanks for the investigation @ReenigneArcher

**Comment by dueler-x** [comment]
> @evoactivity I haven't looked at the code for your script, but my python script returns a key error on the NewsmaxTV channel mentioned in this issue. It's because the json is missing the `thumbnail` key. I had to add error handling to ignore the key errors and make the value blank if there was a key error.
> 
> ![image](https://user-images.githubusercontent.com/42013603/102731298-6e569e80-4305-11eb-8ef7-52131500d112.png)
> 
> Where as it should contain the thumbnail\path.
> ![image](https://user-images.githubusercontent.com/42013603/102731353-99d98900-4305-11eb-87fd-08771b9004ca.png)
> 
> All of these channels are missing something in at least 1 airing.
> `The following json key_errors were found. :[u"program title: Newsmax Live channelName: NewsmaxTV KeyError: 'thumbnail'", u"program title: The Litter channelName: Cats 24/7 KeyError: 'featuredImage'", u"program title: Are You Kitten Me? channelName: Cats 24/7 KeyError: 'featuredImage'", u"program title: Meowathon! channelName: The Pet Collective KeyError: 'featuredImage'", u"program title: Meowathon! channelName: The Pet Collective KeyError: 'featuredImage'", u"program title: Newsmax Live channelName: NewsmaxTV 2 KeyError: 'thumbnail'"]`
> 
> Hope it helps!

Thanks for the investigation @ReenigneArcher, i confirm the script has been working flawlessly for some time this error was breaking my head.

**Comment by ReenigneArcher** [comment]
@dueler-x no problem. I probably would have never known about it had all the keys been present when I wrote my script.

BTW... how are you guys playing these streams? I'm having a lot of issues using VLC/ffmpeg whenever it's time for commercials. I've been reading a lot and pretty much everyone has the same problem.

**Comment by evoactivity** [comment]
@ReenigneArcher I actually gave up trying to use these streams because of that. Pluto do something strange with the stream when ads play but I've never had the time to investigate the stream itself.

**Comment by ReenigneArcher** [comment]
@evoactivity I found a program called streamlink. It's on github. Plays pluto streams perfectly. Need to change the url though... `pluto.tv/live-tv/<channel-slug>`

**Comment by jesusvito** [comment]
Hello everyone! I do not intend to bother you... I just can't find any available PlutoTV m3u playlist(s) with latin american (mexican) content (channels)... I have no clue how could i ever get them in order for me to see them on any iptv app.

I've found this "all region" playlist but lacks LATAM (latin american channels)
PlutoTV: https://i.mjh.nz/PlutoTV/all.m3u8

Thank you !

**Comment by ReenigneArcher** [comment]
@jesusvito I have scripts in this repo that grab many spanish channels. M3u and epg.

https://github.com/ReenigneArcher/web2tv

**Comment by jesusvito** [comment]
> @jesusvito I have scripts in this repo that grab many spanish channels. M3u and epg.
> 
> https://github.com/ReenigneArcher/web2tv

You are most kind! But i'm hopeless since i have no idea how to do it myself :/ i'm sorry. I wish you could help me getting the channels :s. Thanks you so much in advance!

**Comment by evoactivity** [comment]
> @evoactivity I found a program called streamlink. It's on github. Plays pluto streams perfectly. Need to change the url though... `pluto.tv/live-tv/<channel-slug>`
Interesting, I'd come across streamlink before but only looks to have added pluto this November.
It seems people do run into this same issue though https://github.com/streamlink/streamlink/issues/3462

**Comment by evoactivity** [comment]
I'm going to close this issue in favour of a new one to dicuss possible work-arounds for the commercial problem #7
